import { InventoryItem } from '../types/inventory'

// Full inventory seed data parsed from Inventory Report 2025.CSV
export const inventorySeed: InventoryItem[] = [
  // --- Inventory (general / unassigned vendor) ---
  { id: 'INV-00000036', itemCode: '00000036', description: 'Kleen And Kare NSS Irrigation 1L', vendor: 'General', category: '', prefVendor: '', reorderPt: null, onHand: 12, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0.2, rowType: 'item' },
  { id: 'INV-00000832', itemCode: '00000832', description: 'Betamed (Povidone Iodine 10%) 450ml', vendor: 'General', category: '', prefVendor: '', reorderPt: null, onHand: 4115, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 35.7, rowType: 'item' },
  { id: 'INV-830', itemCode: '830', description: 'Betamed (Povidone Iodine 10%) 30ml', vendor: 'General', category: '', prefVendor: '', reorderPt: null, onHand: 2257, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 46.3, rowType: 'item' },
  { id: 'INV-831', itemCode: '831', description: 'Betamed (Povidone Iodine 10%) 15ml', vendor: 'General', category: '', prefVendor: '', reorderPt: null, onHand: 3999, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 12.9, rowType: 'item' },

  // --- A.N.B. Laboratories ---
  { id: 'ANB-8854060000010', itemCode: '8854060000010', description: 'IZE Jelly Balm 7G', vendor: 'A.N.B. Laboratories', category: '', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },

  // A.N.B. > Common Solutions
  { id: 'ANB-CS-1A423-28', itemCode: '1A 423/28', description: 'D5 Water 250mL', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: 'A.N.B Laboratories', reorderPt: null, onHand: 15240, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1475.9, rowType: 'item' },
  { id: 'ANB-CS-1A423-28-1L', itemCode: '1A 423/28-1000mL', description: 'Dextrose 5% in Distilled Water 1L (closed system)', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 2797, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 59.1, rowType: 'item' },
  { id: 'ANB-CS-1A423-28-500mL', itemCode: '1A 423/28-500mL', description: 'Dextrose 5% in Distilled Water 500mL (closed system)', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 4880, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 447.2, rowType: 'item' },
  { id: 'ANB-CS-1A424-28-1L', itemCode: '1A 424/28-1L', description: 'Isotonic Sodium Chloride 1L (closed system)', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 329316, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 13137.3, rowType: 'item' },
  { id: 'ANB-CS-1A424-28-250mL', itemCode: '1A 424/28-250mL', description: 'Isotonic Sodium Chloride (PNSS) 250mL', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 33133, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 3381.6, rowType: 'item' },
  { id: 'ANB-CS-1A424-28-500mL', itemCode: '1A 424/28-500mL', description: 'Isotonic Sodium Chloride 500ml (closed system)', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 72615, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 3841.1, rowType: 'item' },
  { id: 'ANB-CS-1A843-29-1L', itemCode: '1A 843/29-1L', description: 'Sterile Water for Injection 1L (closed system)', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 8236, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 2689.6, rowType: 'item' },
  { id: 'ANB-CS-2A190-27-1L', itemCode: '2A 190/27-1L', description: "Lactated Ringer's Injection 1L (closed system)", vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 49172, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 3247.6, rowType: 'item' },
  { id: 'ANB-CS-2A190-27-500mL', itemCode: '2A 190/27-500mL', description: "Lactated Ringer's Injection 500mL (closed system)", vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 5360, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 326.4, rowType: 'item' },
  { id: 'ANB-CS-2A42-26-1L', itemCode: '2A 42/26-1L', description: 'Dextrose 5% in 1/3 Normal Saline 1L (closed system)', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 6420, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 122.7, rowType: 'item' },
  { id: 'ANB-CS-2A42-26-500mL', itemCode: '2A 42/26-500mL', description: 'Dextrose 5% in 1/3 Normal Saline 500ml (closed system)', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 4054, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 655.5, rowType: 'item' },
  { id: 'ANB-CS-2A79-50', itemCode: '2A 79/50', description: "D5 Lactated Ringer's Injection 1L (closed system)", vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 24177, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1691.3, rowType: 'item' },
  { id: 'ANB-CS-2A79-50-500mL', itemCode: '2A 79/50-500mL', description: "D5 Lactated Ringer's Injection 500ml (closed system)", vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 180, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 639, rowType: 'item' },
  { id: 'ANB-CS-2A1017-27-1L', itemCode: '2A1017/27-1L', description: 'Dextrose 5% in Normal Saline 1L (closed system)', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 1613, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 337, rowType: 'item' },
  { id: 'ANB-CS-2A1017-27-500mL', itemCode: '2A1017/27-500mL', description: 'Dextrose 5% in Normal Saline 500mL (closed system)', vendor: 'A.N.B. Laboratories', category: 'Common Solutions', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },

  // A.N.B. > Mannitol
  { id: 'ANB-MAN-1A552-33-100mL', itemCode: '1A 552/33-100mL', description: 'Mannitol 20% 100 ml (closed system)', vendor: 'A.N.B. Laboratories', category: 'Mannitol', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ANB-MAN-1A552-33-500mL', itemCode: '1A 552/33-500mL', description: '20% Mannitol A.N.B 500ml (closed system)', vendor: 'A.N.B. Laboratories', category: 'Mannitol', prefVendor: '', reorderPt: null, onHand: 5620, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 450.1, rowType: 'item' },

  // A.N.B. > MiniSol
  { id: 'ANB-MINI-100-1A843', itemCode: '100/1A 843/29', description: 'Sterile Water for Injection 100mL (closed system)', vendor: 'A.N.B. Laboratories', category: 'MiniSol', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 9740, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 603.3, rowType: 'item' },
  { id: 'ANB-MINI-1A423-100mL', itemCode: '1A 423/28-100mL', description: 'Dextrose 5% in Distilled Water 100mL (closed system)', vendor: 'A.N.B. Laboratories', category: 'MiniSol', prefVendor: '', reorderPt: null, onHand: 882, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 273.9, rowType: 'item' },
  { id: 'ANB-MINI-1A424-100', itemCode: '1A 424/28-100', description: 'Isotonic Sodium Chloride (Plain NSS 100ml-MiniSol)', vendor: 'A.N.B. Laboratories', category: 'MiniSol', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 213701, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 12423.1, rowType: 'item' },
  { id: 'ANB-MINI-1A424-50mL', itemCode: '1A 424/28-50mL', description: 'Isotonic Sodium Chloride (Plain NSS 50ml-MiniSol)', vendor: 'A.N.B. Laboratories', category: 'MiniSol', prefVendor: '', reorderPt: null, onHand: 39654, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 5631.6, rowType: 'item' },

  // A.N.B. > PNSS Irrigation
  { id: 'ANB-PNSS-1A1721-1L', itemCode: '1A 1721/30-1L', description: 'Normal Saline Irrigating solution 1L (resealable cap)', vendor: 'A.N.B. Laboratories', category: 'PNSS Irrigation', prefVendor: '', reorderPt: null, onHand: 72824, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 4517.2, rowType: 'item' },
  { id: 'ANB-PNSS-1A1721-500mL', itemCode: '1A 1721/30-500mL', description: 'Normal Saline Irrigating 500ml (resealable cap)', vendor: 'A.N.B. Laboratories', category: 'PNSS Irrigation', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },

  // A.N.B. > Special Solutions
  { id: 'ANB-SS-1A348-500mL', itemCode: '1A 348/28-500mL', description: 'D10% Water 500mL (closed system)', vendor: 'A.N.B. Laboratories', category: 'Special Solutions', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ANB-SS-1A424-2L', itemCode: '1A 424/28-2L', description: 'Isotonic Sodium Chloride 2L', vendor: 'A.N.B. Laboratories', category: 'Special Solutions', prefVendor: '', reorderPt: null, onHand: 3882, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 503.8, rowType: 'item' },
  { id: 'ANB-SS-2A304-32', itemCode: '2A 304/32', description: "Acetate Ringer's Injection 1L (closed system)", vendor: 'A.N.B. Laboratories', category: 'Special Solutions', prefVendor: '', reorderPt: null, onHand: 37545, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1382.5, rowType: 'item' },
  { id: 'ANB-SS-2A45-26-1L', itemCode: '2A 45/26-1L', description: 'Dextrose 5% in 1/2 Normal Saline 1L (closed system)', vendor: 'A.N.B. Laboratories', category: 'Special Solutions', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 2686, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 512.5, rowType: 'item' },
  { id: 'ANB-SS-2A45-26-500mL', itemCode: '2a 45/26-500ml', description: 'Dextrose 5% in 1/2 Normal Saline 500ml (closed system)', vendor: 'A.N.B. Laboratories', category: 'Special Solutions', prefVendor: 'A.N.B Laboratories', reorderPt: null, onHand: 6240, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 523.2, rowType: 'item' },

  // A.N.B. > Sterile Water Irrigation
  { id: 'ANB-SWI-1A259-500mL', itemCode: '1A 259/55-500mL', description: 'Sterile Water for Irrigation ANB 500ml (resealable cap)', vendor: 'A.N.B. Laboratories', category: 'Sterile Water Irrigation', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ANB-SWI-K1A-843', itemCode: 'K1A-843/29', description: 'Sterile Water for Irrigation 1L (resealable cap)', vendor: 'A.N.B. Laboratories', category: 'Sterile Water Irrigation', prefVendor: 'A.N.B Laboratories', reorderPt: null, onHand: 36994, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 3240.7, rowType: 'item' },

  // A.N.B. extra item
  { id: 'ANB-V501A', itemCode: 'V501A 843/29', description: 'Sterile Water for Injection 50mL (vial)', vendor: 'A.N.B. Laboratories', category: '', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 17300, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1914, rowType: 'item' },

  // --- ANDE HEALTH CARE ---
  { id: 'ANDE-150N', itemCode: '150ml-N 60-drops', description: 'SA Soluset 150ml Needleless', vendor: 'ANDE HEALTH CARE', category: '', prefVendor: '', reorderPt: null, onHand: 7513, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 78.3, rowType: 'item' },
  { id: 'ANDE-150Y', itemCode: '150ml-Y 60-drops', description: 'IV Set, Burette 150-ml, Y Port', vendor: 'ANDE HEALTH CARE', category: '', prefVendor: '', reorderPt: null, onHand: 9, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ANDE-BPQN20', itemCode: 'BPQ-N 20-drops', description: 'IV Set (Adult), Needle-free Port', vendor: 'ANDE HEALTH CARE', category: '', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0.6, rowType: 'item' },
  { id: 'ANDE-BPQN60', itemCode: 'BPQ-N 60-drops', description: 'IV Set (pedia), Needle-free Port', vendor: 'ANDE HEALTH CARE', category: '', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ANDE-BPQY20', itemCode: 'BPQ-Y 20-drops', description: 'IV Set (adult), Y Port', vendor: 'ANDE HEALTH CARE', category: '', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ANDE-BPQY60', itemCode: 'BPQ-Y 60-drops', description: 'SA Microset (Pedia) Regular BPQ-Y', vendor: 'ANDE HEALTH CARE', category: '', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 22.9, rowType: 'item' },
  { id: 'ANDE-SXQ07', itemCode: 'SXQ0.7', description: 'Blood Transfusion Set (SHINVA)', vendor: 'ANDE HEALTH CARE', category: '', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },

  // --- EUROMED ---
  { id: 'EUR-788', itemCode: '00000000000788', description: '500ML 5% DEXTROSE IN WATER', vendor: 'EUROMED', category: '', prefVendor: '', reorderPt: null, onHand: 2280, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 4.6, rowType: 'item' },
  { id: 'EUR-267', itemCode: '00000267', description: 'EUROMED LACTATED RINGERS SOLN 1000 ML', vendor: 'EUROMED', category: '', prefVendor: '', reorderPt: null, onHand: 8195, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 211.3, rowType: 'item' },
  { id: 'EUR-292', itemCode: '00000292', description: 'EUROMED 0.9% NACL 1000 ML', vendor: 'EUROMED', category: '', prefVendor: '', reorderPt: null, onHand: 2353, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1518.2, rowType: 'item' },
  { id: 'EUR-299', itemCode: '00000299', description: '1000 ML 0.9% NACL FOR IRRIGATION', vendor: 'EUROMED', category: '', prefVendor: '', reorderPt: null, onHand: 4248, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 10.6, rowType: 'item' },
  { id: 'EUR-300', itemCode: '00000300', description: '1000 ML SWFI (TWIST-OFF)', vendor: 'EUROMED', category: '', prefVendor: '', reorderPt: null, onHand: 3600, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'EUR-118', itemCode: '118', description: '500 ML 5% DEXTROSE IN LRS', vendor: 'EUROMED', category: '', prefVendor: 'Euromed', reorderPt: null, onHand: 1536, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 18.9, rowType: 'item' },
  { id: 'EUR-4800', itemCode: '4800573005015', description: 'DEXTROSE IN 0.9% NACL ( EUROMED )', vendor: 'EUROMED', category: '', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'EUR-739', itemCode: '739', description: 'EUROMED EURO-ION IN D5 WWATER 500ML', vendor: 'EUROMED', category: '', prefVendor: 'Euromed', reorderPt: null, onHand: 4776, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 4.6, rowType: 'item' },
  { id: 'EUR-NM', itemCode: 'NM', description: 'D5 NM 1000mL', vendor: 'EUROMED', category: '', prefVendor: 'Euromed', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },

  // --- FRESENIUS KABI ---
  { id: 'FK-FKSNN500', itemCode: 'FKSNN500ml', description: 'PNSS 500mL', vendor: 'FRESENIUS KABI', category: '', prefVendor: 'Fresenius Kabi', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'FK-NSS1L', itemCode: 'NSS1L', description: 'PNSS 1000mL', vendor: 'FRESENIUS KABI', category: '', prefVendor: 'Fresenius Kabi', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'FK-NSS250', itemCode: 'NSS250', description: 'PNSS 250mL', vendor: 'FRESENIUS KABI', category: '', prefVendor: 'Fresenius Kabi', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'FK-PL1', itemCode: 'PL1', description: 'Plain LRS 1000mL', vendor: 'FRESENIUS KABI', category: '', prefVendor: 'Fresenius Kabi', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },

  // --- OPTIMUM ---
  { id: 'OPT-17HQ', itemCode: '17HQ', description: 'Ben Q-17HQ', vendor: 'OPTIMUM', category: "Dialyzers ('00000220)", prefVendor: '', reorderPt: null, onHand: 1255, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 56.5, rowType: 'item' },
  { id: 'OPT-15HQ', itemCode: '15HQ', description: 'Ben Q-15HQ', vendor: 'OPTIMUM', category: 'Dialyzers', prefVendor: '', reorderPt: null, onHand: 2636, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 30.4, rowType: 'item' },
  { id: 'OPT-16LQ', itemCode: '16LQ', description: 'BENQ-16LQ', vendor: 'OPTIMUM', category: 'Dialyzers', prefVendor: '', reorderPt: null, onHand: 1530, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 35.7, rowType: 'item' },
  { id: 'OPT-19HQ', itemCode: '19HQ', description: 'Ben Q-19HQ', vendor: 'OPTIMUM', category: 'Dialyzers', prefVendor: '', reorderPt: null, onHand: 783, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 29.1, rowType: 'item' },
  { id: 'OPT-78398', itemCode: '78398-060', description: 'Renalin 1L.', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 662, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-816', itemCode: '816', description: 'BIOTEQ BLOOD TUBING SET', vendor: 'OPTIMUM', category: 'Blood Tubing', prefVendor: '', reorderPt: null, onHand: -188, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-8454060', itemCode: '8454060604027', description: 'Isotonic Sodium Chloride (PNNS) 1L', vendor: 'OPTIMUM', category: 'IV Solutions', prefVendor: '', reorderPt: null, onHand: 24671, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1921.2, rowType: 'item' },
  { id: 'OPT-CB25', itemCode: 'CB-25-2C', description: 'Bicarb Powder', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: '', reorderPt: null, onHand: 780, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 46.5, rowType: 'item' },
  { id: 'OPT-CS30', itemCode: 'CS-30', description: 'Citrisol 30%', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 574, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 25.7, rowType: 'item' },
  { id: 'OPT-CS50', itemCode: 'CS-50', description: 'Citrisol 50%, Citric Acid Solution 5L', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: '', reorderPt: null, onHand: 717, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 19.1, rowType: 'item' },
  { id: 'OPT-DC112', itemCode: 'DC-112', description: 'Dialysis Powder', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: '', reorderPt: null, onHand: 164, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 8, rowType: 'item' },
  { id: 'OPT-DC116', itemCode: 'DC-116', description: 'Dialysis Powder', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: '', reorderPt: null, onHand: 1285, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 42.4, rowType: 'item' },
  { id: 'OPT-DR120', itemCode: 'DR-120', description: 'DR-120 Acid Powder Concentrate 25gal-bag', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: '', reorderPt: null, onHand: 355, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-DR130', itemCode: 'DR-130', description: 'DR-130 Acid Powder Concentrate 25gal.-bag', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: '', reorderPt: null, onHand: 99, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-DR230', itemCode: 'DR-230', description: 'DR-230 ACID POWDER CONCENTRATE', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 44, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-E09541', itemCode: 'E09541', description: "A.V. Fistula Needle 15Gx1' (PERFECT)", vendor: 'OPTIMUM', category: 'Needles', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 7999, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-E09641', itemCode: 'E09641', description: "AV Fistula Needle 16Gx1' (PERFECT)", vendor: 'OPTIMUM', category: 'Needles', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 49035, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1531.3, rowType: 'item' },
  { id: 'OPT-E09741', itemCode: 'E09741', description: "AV Fistula Needle 17Gx1' (PERFECT)", vendor: 'OPTIMUM', category: 'Needles', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 5149, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 194.8, rowType: 'item' },
  { id: 'OPT-E10154', itemCode: 'E10154', description: 'EXTENSION SET 2.5*4.1*30CM LOCK', vendor: 'OPTIMUM', category: 'Extension Sets', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-NSS1L', itemCode: 'NSS1L (OPTIMUM)', description: 'PNSS 1000ml (FRESENIUS)', vendor: 'OPTIMUM', category: 'IV Solutions', prefVendor: '', reorderPt: null, onHand: 200, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-P5450', itemCode: 'P5450047000', description: 'Execlean', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 913, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 50.9, rowType: 'item' },
  { id: 'OPT-PF89LT', itemCode: 'PF-89-1-LT', description: 'Blood Tubing Set - Long Tip', vendor: 'OPTIMUM', category: 'Blood Tubing', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-PF89LTNT', itemCode: 'PF-89-1-LT-NT', description: 'Blood Tubing Set Without Transducer', vendor: 'OPTIMUM', category: 'Blood Tubing', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-PF89LTP', itemCode: 'PF-89-1-LT-P', description: 'Blood Tubing Set with Pillow, Long Tip', vendor: 'OPTIMUM', category: 'Blood Tubing', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-PF89ST', itemCode: 'PF-89-1-ST', description: 'Bloodlines Short Tip', vendor: 'OPTIMUM', category: 'Blood Tubing', prefVendor: '', reorderPt: null, onHand: 55220, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1593.9, rowType: 'item' },
  { id: 'OPT-PF89STP', itemCode: 'PF-89-1-ST-P', description: 'Bloodlines Short Tip with Pillow', vendor: 'OPTIMUM', category: 'Blood Tubing', prefVendor: '', reorderPt: null, onHand: 4446, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 473.2, rowType: 'item' },
  { id: 'OPT-PF89STR3', itemCode: 'PF-89-1-ST(R3)', description: 'Bloodlines Short Tip (R3)', vendor: 'OPTIMUM', category: 'Blood Tubing', prefVendor: '', reorderPt: null, onHand: -1176, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 23.4, rowType: 'item' },
  { id: 'OPT-PF89STPR3', itemCode: 'PF-89-1-STP(R3)', description: "Bloodlines w/ Pillow (R3)", vendor: 'OPTIMUM', category: 'Blood Tubing', prefVendor: '', reorderPt: null, onHand: 634, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'OPT-PH4', itemCode: 'PH4', description: 'Platinum H4', vendor: 'OPTIMUM', category: 'Dialyzers', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 6300, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 109.8, rowType: 'item' },
  { id: 'OPT-PS130', itemCode: 'PS130', description: 'Polysulfonate Dialyzer 1.3 sqm.', vendor: 'OPTIMUM', category: 'Dialyzers', prefVendor: '', reorderPt: null, onHand: 2500, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 24.2, rowType: 'item' },
  { id: 'OPT-PS160', itemCode: 'PS160', description: 'Polysulfonate Dialyzer 1.6 sqm.', vendor: 'OPTIMUM', category: 'Dialyzers', prefVendor: '', reorderPt: null, onHand: 1164, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 15.2, rowType: 'item' },
  { id: 'OPT-PS180', itemCode: 'PS180', description: 'Polysulfonate Dialyzer 1.8 sqm.', vendor: 'OPTIMUM', category: 'Dialyzers', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 3742, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 76.3, rowType: 'item' },
  { id: 'OPT-RB02', itemCode: 'RB02-20C', description: 'Bicarbonate Powder Concentrate (box)', vendor: 'OPTIMUM', category: 'Dialysis Supplies', prefVendor: '', reorderPt: null, onHand: 94, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },

  // --- PERFECT MEDICAL ---
  { id: 'PM-E07761L', itemCode: 'E07761L', description: 'Hemodialysis Blood Tubing set', vendor: 'PERFECT MEDICAL', category: 'Hemodialysis', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'PM-E04757P', itemCode: 'E04757P', description: 'PF Macroset (Adult) Needleless E04757P', vendor: 'PERFECT MEDICAL', category: 'IV Sets - Needleless', prefVendor: '', reorderPt: null, onHand: 21587, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1413.6, rowType: 'item' },
  { id: 'PM-E04853P', itemCode: 'E04853P', description: 'PF Microset (Pedia) Needleless E04853P', vendor: 'PERFECT MEDICAL', category: 'IV Sets - Needleless', prefVendor: '', reorderPt: null, onHand: 23593, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 727.8, rowType: 'item' },
  { id: 'PM-E05221P', itemCode: 'E05221P', description: 'PF Soluset 120ml Needleless E05221P', vendor: 'PERFECT MEDICAL', category: 'IV Sets - Needleless', prefVendor: '', reorderPt: null, onHand: 9840, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 556.1, rowType: 'item' },
  { id: 'PM-E04757A', itemCode: 'E04757A', description: 'PF Macroset (Adult) Regular E04757A', vendor: 'PERFECT MEDICAL', category: 'IV Sets - Regular', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 30580, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1588.4, rowType: 'item' },
  { id: 'PM-E04853B', itemCode: 'E04853B', description: 'PF Microset (Pedia) Regular E04853B', vendor: 'PERFECT MEDICAL', category: 'IV Sets - Regular', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 4100, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 389, rowType: 'item' },
  { id: 'PM-E05221B', itemCode: 'E05221B', description: 'PF Soluset 120ml Regular E05221B', vendor: 'PERFECT MEDICAL', category: 'IV Sets - Regular', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 16260, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 1433.2, rowType: 'item' },
  { id: 'PM-E06162', itemCode: 'E06162', description: 'PF Blood Transfusion set E06162', vendor: 'PERFECT MEDICAL', category: 'IV Sets - Regular', prefVendor: 'Optimum Trading Co.', reorderPt: null, onHand: 11176, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 215.1, rowType: 'item' },

  // --- T432158 (standalone) ---
  { id: 'ZUELLIG-T432158', itemCode: 'T432158', description: 'Compoflex Quadruple T&B', vendor: 'ZUELLIG', category: '', prefVendor: 'Zuellig Pharma Corporation', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 12.9, rowType: 'item' },

  // --- ZAFIRE DISTRIBUTORS INC. ---
  { id: 'ZAF-A4R7473', itemCode: 'A4R7473', description: 'Quad Optipack', vendor: 'ZAFIRE DISTRIBUTORS INC.', category: '', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },

  // --- ZUELLIG ---
  { id: 'ZUE-782', itemCode: '00000000000782', description: 'D5 NM 500ml (B-Braun)', vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ZUE-737', itemCode: '00000000737', description: "D5 Bal. Multi Maint Sol'n 500ml (Bbraun)", vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 34.1, rowType: 'item' },
  { id: 'ZUE-738', itemCode: '00000000738', description: "D5 Bal. Mutli Maint Sol'n 1L (Bbraun)", vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ZUE-739', itemCode: '00000000739', description: 'D5 LR 1000ml (BBraun)', vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ZUE-740', itemCode: '00000000740', description: 'PLAIN LR 1000ML (Bbraun)', vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ZUE-741', itemCode: '00000000741', description: 'D5 Water 500 ml (Bbraun)', vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 47.8, rowType: 'item' },
  { id: 'ZUE-0000018', itemCode: '0000018', description: 'D5 LRS 500ml (Bbraun)', vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ZUE-110940992', itemCode: '110940992', description: 'Isotonic Sodium Chloride 500ml-ECOFLAC', vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 57.5, rowType: 'item' },
  { id: 'ZUE-110940994', itemCode: '110940994', description: "Lactated Ringer's 1L-ECOFLAC", vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 11.7, rowType: 'item' },
  { id: 'ZUE-110941227', itemCode: '110941227', description: 'PLAIN LR 500 ml (Bbraun)', vendor: 'ZUELLIG', category: 'B-Braun', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ZUE-836', itemCode: '836', description: 'SODIUM CHLORIDE 0.9% SOLN EP 1000ml', vendor: 'ZUELLIG', category: 'B/Braun Clinical Nutrition', prefVendor: '', reorderPt: null, onHand: 11071, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 171.2, rowType: 'item' },
  { id: 'ZUE-H6030', itemCode: 'H6030', description: 'Dobutamine 250mg/250mL', vendor: 'ZUELLIG', category: 'Inotropes', prefVendor: 'Bohol Medical Care Institute', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ZUE-H6031', itemCode: 'H6031', description: 'Dobutamine 500mg/250mL', vendor: 'ZUELLIG', category: 'Inotropes', prefVendor: 'Bohol Medical Care Institute', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ZUE-H6041', itemCode: 'H6041', description: 'Dopamine 200mg/250mL', vendor: 'ZUELLIG', category: 'Inotropes', prefVendor: '', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
  { id: 'ZUE-H6042', itemCode: 'H6042', description: 'Dopamine HCL 400mg/250mL', vendor: 'ZUELLIG', category: 'Inotropes', prefVendor: 'Bohol Medical Care Institute', reorderPt: null, onHand: 0, order: null, onPO: 0, nextDeliv: '', salesPerWeek: 0, rowType: 'item' },
]

export const VENDORS = [...new Set(inventorySeed.map(i => i.vendor))].sort()
export const CATEGORIES = [...new Set(inventorySeed.map(i => i.category).filter(Boolean))].sort()
